opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - untyped_error_in_catch
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_between_cases
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

private_over_fileprivate:
  validate_extensions: true
  severity: error

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 2
